default:
  image: $CI_REGISTRY/docker/ansible:latest
  services:
    - name: docker:dind
      alias: dockersvc
      command: [ "--tls=false" ]

stages:
  - test

before_script:
  - docker info

variables:
  DOCKER_HOST: tcp://dockersvc:2375/
  DOCKER_TLS_CERTDIR: ""
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

molecule_test:
  stage: test
  before_script:
    - apk add py3-passlib
  parallel:
    matrix:
      - MOLECULE_DISTRO: ["ubuntu2204","debian10"]
  script:
    - molecule test --all --parallel
  variables:
    MOLECULE_DISTRO: $MOLECULE_DISTRO
  only:
    changes:
      - main
      - "**/*"

